### Step 1 - Login
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "email": "ira@test.com",
  "password": "titty1234"
}
### Get Game State
GET http://127.0.0.1:5000/api/games/c7b1c826-e6c9-49b9-9c51-20620e0123cd/state
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDcwNDAxLCJleHAiOjE3ODg0NzEzMDF9.wYQJlof78Fci9kiP3fKumAMygJWYR9OL4UuczDCbtzg

### Set Phase
POST http://127.0.0.1:5000/api/games/c7b1c826-e6c9-49b9-9c51-20620e0123cd/phase
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDcwNDAxLCJleHAiOjE3ODg0NzEzMDF9.wYQJlof78Fci9kiP3fKumAMygJWYR9OL4UuczDCbtzg

{
  "phase": "VOTING"
}

### End Game
POST http://127.0.0.1:5000/api/games/c7b1c826-e6c9-49b9-9c51-20620e0123cd/end
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDcwNDAxLCJleHAiOjE3ODg0NzEzMDF9.wYQJlof78Fci9kiP3fKumAMygJWYR9OL4UuczDCbtzg

{
  "winner": "DEVELOPERS",
  "winReason": "ALL_MAFIA_ELIMINATED",
  "roomCode": "0E8F1C"
}