### Step 1 - Login
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "email": "ira@test.com",
  "password": "titty1234"
}

### Step 2 - Start Vote
POST http://127.0.0.1:5000/api/games/c7b1c826-e6c9-49b9-9c51-20620e0123cd/vote/start
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDY5MzIyLCJleHAiOjE3ODg0NzAyMjJ9.rjHK5g-cVCR6eG0WqpuRQrRMS-JX6x6HUVjCRVxiPso

{
  "nominatedUserId": "d53a666b-7dc7-4e53-864f-72e319d7d93c",
  "round": 1
}
### Step 3 - Cast Vote
POST http://127.0.0.1:5000/api/games/c7b1c826-e6c9-49b9-9c51-20620e0123cd/vote/cast
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDY5MzIyLCJleHAiOjE3ODg0NzAyMjJ9.rjHK5g-cVCR6eG0WqpuRQrRMS-JX6x6HUVjCRVxiPso


{
  "voteRoundId": "f861cec8-4fc1-4653-b3b3-d9ae5723e286",
  "gamePlayerId": "bbafd40a-1f3c-4b8a-9fc4-18decf78870f",
  "inFavor": true
}

### Step 4 - Vote Status
GET http://127.0.0.1:5000/api/vote/f861cec8-4fc1-4653-b3b3-d9ae5723e286/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDY5MzIyLCJleHAiOjE3ODg0NzAyMjJ9.rjHK5g-cVCR6eG0WqpuRQrRMS-JX6x6HUVjCRVxiPso


### Step 5 - Resolve Vote
POST http://127.0.0.1:5000/api/vote/f861cec8-4fc1-4653-b3b3-d9ae5723e286/resolve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhODA5OTNmLTU3MWUtNDcyYS1iMjZiLTBjNGY3OTQxZmY3YiIsInVzZXJuYW1lIjoiaXJhIiwiaWF0IjoxNzg4NDY5MzIyLCJleHAiOjE3ODg0NzAyMjJ9.rjHK5g-cVCR6eG0WqpuRQrRMS-JX6x6HUVjCRVxiPso

{
  "roomCode": "0E8F1C"
}