const prisma = require("../../../config/prisma.js");

/**
 * Log a player activity and calculate its suspicion impact.
 */
async function logActivity({
    gameId,
    userId,
    filename,
    changeType,
    linesChanged,
    diff,
}) {
    let suspicionDelta = 0;

    if (changeType === "REMOVE" && linesChanged > 5) {
        suspicionDelta = 10;
    } else if (changeType === "MODIFY") {
        suspicionDelta = 5;
    } else if (changeType === "ADD") {
        suspicionDelta = 0;
    }

    const activity = await prisma.activityLog.create({
        data: {
            gameId,
            userId,
            filename,
            changeType,
            linesChanged,
            diff,
            suspicionDelta,
        },
    });

    return activity;
}

/**
 * Public activity feed.
 * Does not expose diff or suspicionDelta.
 */
async function getActivityFeed(gameId) {
    const activities = await prisma.activityLog.findMany({
        where: {
            gameId,
        },
        orderBy: {
            timestamp: "desc",
        },
        include: {
            user: {
                select: {
                    id: true,
                    username: true,
                },
            },
        },
    });

    return activities.map((activity) => ({
        username: activity.user.username,
        filename: activity.filename,
        changeType: activity.changeType,
        linesChanged: activity.linesChanged,
        timestamp: activity.timestamp,
    }));
}

/**
 * INTERNAL ONLY.
 *
 * Calculates suspicion scores using activity logs and test results.
 * Do not expose this function through a public REST endpoint.
 */
async function getSuspicionScores(gameId) {
    const activities = await prisma.activityLog.findMany({
        where: {
            gameId,
        },
        include: {
            user: {
                select: {
                    id: true,
                    username: true,
                },
            },
        },
    });

    const executions = await prisma.executionLog.findMany({
        where: {
            gameId,
        },
        include: {
            user: {
                select: {
                    id: true,
                    username: true,
                },
            },
        },
    });

    const scores = new Map();

    // Add suspicion generated by code activity.
    for (const activity of activities) {
        if (!scores.has(activity.userId)) {
            scores.set(activity.userId, {
                userId: activity.userId,
                username: activity.user.username,
                suspicionScore: 0,
            });
        }

        scores.get(activity.userId).suspicionScore +=
            activity.suspicionDelta || 0;
    }

    // Factor in test execution results.
    for (const execution of executions) {
        if (!scores.has(execution.userId)) {
            scores.set(execution.userId, {
                userId: execution.userId,
                username: execution.user.username,
                suspicionScore: 0,
            });
        }

        const score = scores.get(execution.userId);

        score.suspicionScore -= (execution.testsPassed || 0) * 5;
        score.suspicionScore += (execution.testsFailed || 0) * 10;
    }

    return Array.from(scores.values()).sort(
        (a, b) => b.suspicionScore - a.suspicionScore
    );
}

/**
 * Calculate a player's updated suspicion after a test run.
 */
async function updateSuspicionOnTest({
    gameId,
    userId,
    testsPassed,
    testsFailed,
}) {
    const activities = await prisma.activityLog.findMany({
        where: {
            gameId,
            userId,
        },
        select: {
            suspicionDelta: true,
        },
    });

    const activitySuspicion = activities.reduce(
        (total, activity) => total + (activity.suspicionDelta || 0),
        0
    );

    const updatedScore =
        activitySuspicion +
        (testsFailed || 0) * 10 -
        (testsPassed || 0) * 5;

    return {
        userId,
        updatedScore,
    };
}

module.exports = {
    logActivity,
    getActivityFeed,
    getSuspicionScores,
    updateSuspicionOnTest,
};